from entities.location import Location
class List_main():
    def __init__(self):
        self.list_name = ""
        self.list_of_location = []

    def fill_lications(self):
        self.list_name = "Основной"
        terrorists_base = Location("База террористов", "images/terror_base.jpg")
        self.list_of_location.append(terrorists_base)
        bank = Location("Банк", "images/bank.jpg")
        self.list_of_location.append(bank)
        hospital = Location("Больница", "images/hospital.jpg")
        self.list_of_location.append(hospital)
        film_studio = Location("Киностудия", "images/kinostudio.jpg")
        self.list_of_location.append(film_studio)
        corporate_disco = Location("Корпоратив", "images/corporate_disco.jpg")
        self.list_of_location.append(corporate_disco)
        cons_lager = Location("Концлагерь", "images/kinostudio.jpg")
        self.list_of_location.append(cons_lager)
        partisane_team = Location("Партизанский отряд", "images/partisane_team.jpg")
        self.list_of_location.append(partisane_team)
        train = Location("Пассажирский поезд", "images/train.jpg")
        self.list_of_location.append(train)
        pirate_ship = Location("Пиратский корабль", "images/pirate_ship.jpg")
        self.list_of_location.append(pirate_ship)
        capital_of_polar = Location("Полярная станция", "images/polar_station.jpg")
        self.list_of_location.append(capital_of_polar)
        embassy = Location("Посольство", "images/embassy.jpg")
        self.list_of_location.append(embassy)
        restoran = Location("Ресторан", "images/restouran.jpg")
        self.list_of_location.append(restoran)
        supermarket = Location("Супермаркет", "images/supermarket.jpg")
        self.list_of_location.append(supermarket)
        theater = Location("Театр", "images/teather.jpg")
        self.list_of_location.append(theater)
        university = Location("Университет", "images/university.jpg")
        self.list_of_location.append(university)
        military_union = Location("Воинская часть", "images/military_union.jpg")
        self.list_of_location.append(military_union)
        crusaders_army = Location("Войско крестоносцев", "images/crusaders.jpg")
        self.list_of_location.append(crusaders_army)
        casino = Location("Казино", "images/casino.jpg")
        self.list_of_location.append(casino)
        ocean_liner = Location("Океанский лайнер", "images/ship.jpg")
        self.list_of_location.append(ocean_liner)
        orbital_station = Location("Орбитальная станция", "images/space_station.jpg")
        self.list_of_location.append(orbital_station)
        hotel = Location("Отель", "images/hotel.jpg")
        self.list_of_location.append(hotel)
        beach = Location("Пляж", "images/beach.jpg")
        self.list_of_location.append(beach)
        underwater_ship = Location("Подводная лодка", "images/underwater_sheep.jpg")
        self.list_of_location.append(underwater_ship)
        police_station = Location("Полицейский участок", "images/police.jpg")
        self.list_of_location.append(police_station)
        plane = Location("Самолет", "images/airplane.jpg")
        self.list_of_location.append(plane)
        spa_saloon = Location("Спа-салон", "images/spa.jpg")
        self.list_of_location.append(spa_saloon)
        sto = Location("СТО", "images/sto.jpg")
        self.list_of_location.append(sto)
        chirch = Location("Церковь", "images/chirch.jpg")
        self.list_of_location.append(chirch)
        circus = Location("Цирк", "images/circus.jpg")
        self.list_of_location.append(circus)
        school = Location("Школа", "images/school.jpg")
        self.list_of_location.append(school)